---
abstract: 'Simple REST endpoint app for db backend build with Plack and DBIC'
author:
  - 'Tomasz Czepiel <tjmc@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Plack::Test: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hyle
no_index:
  directory:
    - t
    - inc
requires:
  Class::Load: 0
  DBI: 0
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0
  File::Temp: 0
  Getopt::Long: 0
  HTTP::Message: 0
  Hash::MultiValue: 0
  JSON: 0
  Package::Stash: 0
  Plack: 0
  URI::Escape: 0
  parent: 0
resources:
  repository: git://github.com/tczepiel/perl-app-hyle.git
version: 0.4
